DROP TRIGGER IF EXISTS update_timestamp_trigger ON USERS;

DROP FUNCTION IF EXISTS update_timestamp();

DROP TABLE USER_TOKENS;

DROP TABLE TOKEN_TYPES;

DROP TABLE REFRESH_TOKENS;

DROP TABLE USERS;

DROP TABLE ROLE_TYPES;