env: "local"

http:
  host: "0.0.0.0"
  port: 8000
  maxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth-service:
  http:
    schema: "http"
    host: "localhost"
    port: 8080

data-service:
  http:
    schema: "http"
    host: "109.172.81.237"
    port: 8888
